INSERT INTO T_USER (ID,FIRST_NAME,LAST_NAME) VALUES (USER_SEQUENCE.NEXTVAL, 'John','Doe');



INSERT INTO T_PREFERENCE (CITY,STATE,USER_ID,NOTIFY_CYCLE_MINS,IS_SMS_ACTIVE,IS_MAIL_ACTIVE
,IS_APP_NOTIFY_ACTIVE, THRESHOLD) VALUES ('San Francisco','CA', 1,2,'Y','N','Y',1);



INSERT INTO T_TEMPERATURE (CITY,PROVIDER_ID,CODE,CREDITS,STATE,VISIBILITY_MILES,WIND_MPH,
    TEMP_C,TEMP_F,RELATIVE_HUMIDITY,WIND_DIR) VALUES
    ('San Francisco', 1,'SUCCESS', '499999978','CA','10.00','17.3', 22.2, 72.0, 57, 'West');



INSERT INTO T_PROVIDER (PROVIDER_ID,PROVIDER_NAME,URI) VALUES (PROVIDER_SEQUENCE.NEXTVAL, 'IMD','DUMMY');
INSERT INTO T_PROVIDER (PROVIDER_ID,PROVIDER_NAME,URI) VALUES (PROVIDER_SEQUENCE.NEXTVAL, 'WeatherAPI','DUMMY');
